[package]
name = "dwsh-utils"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"

[dependencies]
serde = "1.0.228"
toml = "0.9.8"
iced = { version = "0.13.1", features = ["tokio"] }
